# Generated by Django 4.1.5 on 2023-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("M", "Male"), ("O", "Others")],
                max_length=1,
                null=True,
            ),
        ),
    ]
