# Generated by Django 4.1.5 on 2023-05-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name_invoice", models.CharField(max_length=100)),
                ("address_invoice", models.TextField(blank=True, max_length=150)),
                ("GST_invoice", models.CharField(blank=True, max_length=100)),
                ("invoice_number", models.CharField(max_length=100)),
                ("date_added_invoice", models.DateField(auto_now_add=True)),
                ("particular_invoice", models.CharField(blank=True, max_length=100)),
                (
                    "amount_invoice",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                (
                    "any_discount_invoice",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20),
                ),
                (
                    "coaching_type_course_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientsapp.course",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_added_invoice",),
            },
        ),
    ]
