# Generated by Django 4.1.5 on 2023-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cgst",
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst",
            field=models.PositiveIntegerField(default=9),
        ),
    ]
