# Generated by Django 4.1.5 on 2023-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_invoice_cgst_invoice_sgst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="any_discount_invoice",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=20
            ),
        ),
    ]
