# Generated by Django 4.1.5 on 2023-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_alter_invoice_any_discount_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_amount_invoice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount_invoice",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="any_discount_invoice",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20
            ),
        ),
    ]
