# Generated by Django 4.1.5 on 2023-05-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_invoice_total_amount_payable_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="particular_invoice",
            field=models.TextField(blank=True),
        ),
    ]
